name: ci

on: 
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests

  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 gofast

      - name: Lint with pylint
        run: pylint gofast

      - name: Lint tests with flake8
        run: flake8 tests

      - name: Lint tests with pylint
        run: pylint tests

  security:
    name: security
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check security of gofast with bandit
      run: bandit -r gofast

    - name: Check security of tests with bandit
      run: bandit -r tests
